### ISSUE TITLE
BPT

### ISSUE THREAD

**Issue by JulissaDantes** [justsomegeeks/enzyme-balancer#5]
Our Goal:  Price a BPT
We just need to write an adapter that takes the total value of each token in a balancer pool at the time of execution and divides it by the total number of bpt in circulation... so we'll need to aggregate the prices for each pool,  have acces to the total number of each token in the pool and the total number of bpt.  we should be able to get the prices from chainlink and the token supplies from balancer.

The best way to price a BPT is to find the value of all the pool's tokens and just divide by the total supply of BPT, I see that Enzyme uses chainlink price feeds so you could likely make use of these.

Edit: For the scope of the EthOnline event we will just consider the main pools.

Tasks:
- [x] Check the code behind the pool dashboard t see how the $61.82 was calculated
- [x] Be able to get total supply for specific Balancer pool
- [x] Create `BalancerV2PriceFeed.sol` contract with `getPoolInfoFromPool` implementation and `getTokensFromPool` implementation, since those are the functions being use inside the example. Both functions can be found inside the balancer Vault(`PoolTokens` inner contract for reference)
- [x] Compute BPT inside the smart contract

Contract where we find the redeem function: [BalancerV2ActionsMixin.sol](https://github.com/justsomegeeks/enzyme-balancer/blob/main/contracts/BalancerV2ActionsMixin.sol)

**Comment by MrDeadCe11** [comment]
- [ ] find total supply of each individual token in a balancer pool.

**Comment by JulissaDantes** [comment]
Documentation: Instead of each pool holding its tokens, Balancer V2 is built on a single Vault that holds and manages the assets of all Balancer pools.

We can use the Balancer vault to accomplish the task of finding the supply of each individual token in a balancer pool without having to manually to aggregate the prices for each pool since the Balancer Vault is doing that for us

Source: https://docs.balancer.fi/core-concepts/protocol/vault

**Comment by JulissaDantes** [comment]
Documentation:
The `Vault`'s source code is split among a number of sub-contracts, The most important for this task are: [AssetManagers](https://github.com/balancer-labs/balancer-v2-monorepo/blob/master/pkg/vault/contracts/AssetManagers.sol), [PoolTokens](https://github.com/balancer-labs/balancer-v2-monorepo/blob/master/pkg/vault/contracts/PoolTokens.sol), and [PoolBalances](https://github.com/balancer-labs/balancer-v2-monorepo/blob/master/pkg/vault/contracts/PoolBalances.sol).

Source: [Vault contract](https://github.com/balancer-labs/balancer-v2-monorepo/blob/master/pkg/vault/contracts/Vault.sol)

**Comment by JulissaDantes** [comment]
@MrDeadCe11  This is the development outline for getting the BPT price following the formula `BPT PRICE= a/b`( where `a` = BPT pools value, and `b` = TotalSupply of BPT):

1. Use subgraph to get all pools like they do [here](https://github.com/balancer-labs/balancer-sor/blob/7b7ff636378568b08990643f3dd8db2d237e2e53/src/poolCaching/subgraph.ts#L5) using `https://ipfs.fleek.co/ipns/balancer-team-bucket.storage.fleek.co/balancer-exchange/pools` as poolURL.
2. Consult the Vault using the `getPoolTokens` for each id of the previous step and aggregate those values.
3. Get the total supply from the [BPT contract](https://etherscan.io/address/0x6f8a975758436a5ec38d2f9d2336504430465517)
4. Do the math and we have it.

I havent write this code since Im waiting for confirmation on from the balancer team about the `a` value on the ethonline sponsor channel, if you think you can answer that question be my guest, I just want to know what we think we need is actually what we need. **The question** is `a` is the `balanceOf `the BPT token, or the price from a price feed of the BPT token multiplied by the `balanceOf`, or the balanceOf all the tokens in balancer multiplied by the price feed of chainlink?
![image](https://user-images.githubusercontent.com/8561085/134790367-7a227cc0-64ec-4541-8a01-eb7145d1d245.png)

**Comment by JulissaDantes** [comment]
This was the answer to my question from the Balancer team: 1) I mean you can do something like ETH balance of pool * ETH price in USD + BAL balance of pool * BAL price in USDC +... to get the value of the entire pool in USD and then divide by the total supply of BPT as this will give the redemption value of 1 BPT.
2) I'm not sure which pool you're using but it's the result of calling totalSupply on the pool contract (this gives the total supply of the associated BPT token)

**Comment by JulissaDantes** [comment]
This was closed with #29
